// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_editor_state(
    object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
    input: &crate::types::EditorState,
) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.document {
        #[allow(unused_mut)]
        let mut object_2 = object.key("document").start_object();
        crate::protocol_serde::shape_text_document::ser_text_document(&mut object_2, var_1)?;
        object_2.finish();
    }
    if let Some(var_3) = &input.cursor_state {
        #[allow(unused_mut)]
        let mut object_4 = object.key("cursorState").start_object();
        crate::protocol_serde::shape_cursor_state::ser_cursor_state(&mut object_4, var_3)?;
        object_4.finish();
    }
    Ok(())
}
