PLATFORM=$(shell $(ROOT)/systype.sh)

CC=gcc
COMPILE.c=$(CC) $(CFLAGS) $(CPPFLAGS) -c
LINK.c=$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
LDFLAGS=
LDLIBS=-L$(ROOT)/libvterm -L$(ROOT)/lib -lvterm -lfig -lm $(EXTRALIBS)
CFLAGS=-I$(ROOT)/libvterm/include -I$(ROOT)/include -Wall -ggdb -DLINUX -D_GNU_SOURCE $(EXTRA)
AR=ar
AWK=awk

ifeq "$(PLATFORM)" "solaris"
  EXTRALIBS=-lsocket -lnsl
endif
