PLATFORM=$(shell $(ROOT)/systype.sh)

CC=gcc
COMPILE.c=$(CC) $(CFLAGS) $(CPPFLAGS) -c
LINK.c=$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
LDFLAGS=
LDLIBS=$(ROOT)/libvterm/lib/libvterm.a -L$(ROOT)/lib -lfig -lm $(EXTRALIBS)
CFLAGS=-I$(ROOT)/libvterm/include -I$(ROOT)/include -Wall -ggdb $(EXTRA)
AR=ar

ifeq "$(PLATFORM)" "macos"
  CFLAGS+=-D_DARWIN_C_SOURCE
else
  CFLAGS+=-DLINUX -D_GNU_SOURCE
endif

ifeq "$(PLATFORM)" "solaris"
  EXTRALIBS=-lsocket -lnsl
endif
