# Add brackets for zsh only.
# FIG_NEW_CMD=$'%{\e]FIG_NEW_CMD\e\\%}'
# FIG_START_SKIP=$'%{\e]FIG_START_SKIP\e\\%}'
# FIG_END_SKIP=$'%{\e]FIG_END_SKIP\e\\%}'
FIG_NEW_CMD=$'\e]FIG_NEW_CMD\e\\'
FIG_START_SKIP=$'\e]FIG_START_SKIP\e\\'
FIG_END_SKIP=$'\e]FIG_END_SKIP\e\\'

export PS1="$PS1$FIG_NEW_CMD";
export PS2="$FIG_START_SKIP$PS2$FIG_END_SKIP";
export PS3="$PS3$FIG_NEW_CMD";

export PROMPT="$PROMPT$FIG_NEW_CMD";
export PROMPT2="$FIG_START_SKIP$PROMPT2$FIG_END_SKIP";
export PROMPT3="$PROMPT3$FIG_NEW_CMD";

export RPS1="$FIG_START_SKIP$RPS1$FIG_END_SKIP";
export RPROMPT="$FIG_START_SKIP$RPS1$FIG_END_SKIP";
