// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct CreateUploadUrlOutput {
    /// Upload ID returned by CreateUploadUrl API
    pub upload_id: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub upload_url: ::std::string::String,
    #[allow(missing_docs)] // documentation missing in model
    pub kms_key_arn: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl CreateUploadUrlOutput {
    /// Upload ID returned by CreateUploadUrl API
    pub fn upload_id(&self) -> &str {
        use std::ops::Deref;
        self.upload_id.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn upload_url(&self) -> &str {
        use std::ops::Deref;
        self.upload_url.deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn kms_key_arn(&self) -> ::std::option::Option<&str> {
        self.kms_key_arn.as_deref()
    }
}
impl ::std::fmt::Debug for CreateUploadUrlOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("CreateUploadUrlOutput");
        formatter.field("upload_id", &self.upload_id);
        formatter.field("upload_url", &"*** Sensitive Data Redacted ***");
        formatter.field("kms_key_arn", &self.kms_key_arn);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
impl ::aws_types::request_id::RequestId for CreateUploadUrlOutput {
    fn request_id(&self) -> Option<&str> {
        self._request_id.as_deref()
    }
}
impl CreateUploadUrlOutput {
    /// Creates a new builder-style object to manufacture
    /// [`CreateUploadUrlOutput`](crate::operation::create_upload_url::CreateUploadUrlOutput).
    pub fn builder() -> crate::operation::create_upload_url::builders::CreateUploadUrlOutputBuilder {
        crate::operation::create_upload_url::builders::CreateUploadUrlOutputBuilder::default()
    }
}

/// A builder for
/// [`CreateUploadUrlOutput`](crate::operation::create_upload_url::CreateUploadUrlOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
pub struct CreateUploadUrlOutputBuilder {
    pub(crate) upload_id: ::std::option::Option<::std::string::String>,
    pub(crate) upload_url: ::std::option::Option<::std::string::String>,
    pub(crate) kms_key_arn: ::std::option::Option<::std::string::String>,
    _request_id: Option<String>,
}
impl CreateUploadUrlOutputBuilder {
    /// Upload ID returned by CreateUploadUrl API
    /// This field is required.
    pub fn upload_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.upload_id = ::std::option::Option::Some(input.into());
        self
    }

    /// Upload ID returned by CreateUploadUrl API
    pub fn set_upload_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.upload_id = input;
        self
    }

    /// Upload ID returned by CreateUploadUrl API
    pub fn get_upload_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.upload_id
    }

    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn upload_url(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.upload_url = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_upload_url(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.upload_url = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_upload_url(&self) -> &::std::option::Option<::std::string::String> {
        &self.upload_url
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn kms_key_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.kms_key_arn = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_kms_key_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.kms_key_arn = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_kms_key_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.kms_key_arn
    }

    pub(crate) fn _request_id(mut self, request_id: impl Into<String>) -> Self {
        self._request_id = Some(request_id.into());
        self
    }

    pub(crate) fn _set_request_id(&mut self, request_id: Option<String>) -> &mut Self {
        self._request_id = request_id;
        self
    }

    /// Consumes the builder and constructs a
    /// [`CreateUploadUrlOutput`](crate::operation::create_upload_url::CreateUploadUrlOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`upload_id`](crate::operation::create_upload_url::builders::CreateUploadUrlOutputBuilder::upload_id)
    /// - [`upload_url`](crate::operation::create_upload_url::builders::CreateUploadUrlOutputBuilder::upload_url)
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::create_upload_url::CreateUploadUrlOutput,
        ::aws_smithy_types::error::operation::BuildError,
    > {
        ::std::result::Result::Ok(crate::operation::create_upload_url::CreateUploadUrlOutput {
            upload_id: self.upload_id.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "upload_id",
                    "upload_id was not specified but it is required when building CreateUploadUrlOutput",
                )
            })?,
            upload_url: self.upload_url.ok_or_else(|| {
                ::aws_smithy_types::error::operation::BuildError::missing_field(
                    "upload_url",
                    "upload_url was not specified but it is required when building CreateUploadUrlOutput",
                )
            })?,
            kms_key_arn: self.kms_key_arn,
            _request_id: self._request_id,
        })
    }
}
impl ::std::fmt::Debug for CreateUploadUrlOutputBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("CreateUploadUrlOutputBuilder");
        formatter.field("upload_id", &self.upload_id);
        formatter.field("upload_url", &"*** Sensitive Data Redacted ***");
        formatter.field("kms_key_arn", &self.kms_key_arn);
        formatter.field("_request_id", &self._request_id);
        formatter.finish()
    }
}
