// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`CreateProfile`](crate::operation::create_profile::builders::CreateProfileFluentBuilder)
    /// operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`identity_source(IdentitySource)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::identity_source) / [`set_identity_source(Option<IdentitySource>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::set_identity_source): (undocumented)
    ///   - [`profile_name(impl Into<String>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::profile_name) / [`set_profile_name(Option<String>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::set_profile_name): (undocumented)
    ///   - [`reference_tracker_configuration(ReferenceTrackerConfiguration)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::reference_tracker_configuration) / [`set_reference_tracker_configuration(Option<ReferenceTrackerConfiguration>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::set_reference_tracker_configuration): (undocumented)
    ///   - [`client_token(impl Into<String>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::client_token) / [`set_client_token(Option<String>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::set_client_token): (undocumented)
    ///   - [`kms_key_arn(impl Into<String>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::kms_key_arn) / [`set_kms_key_arn(Option<String>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::set_kms_key_arn): (undocumented)
    ///   - [`tags(Tag)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::tags) / [`set_tags(Option<Vec<Tag>>)`](crate::operation::create_profile::builders::CreateProfileFluentBuilder::set_tags): (undocumented)
    /// - On success, responds with
    ///   [`CreateProfileOutput`](crate::operation::create_profile::CreateProfileOutput) with
    ///   field(s):
    ///   - [`profile_arn(Option<String>)`](crate::operation::create_profile::CreateProfileOutput::profile_arn): (undocumented)
    /// - On failure, responds with
    ///   [`SdkError<CreateProfileError>`](crate::operation::create_profile::CreateProfileError)
    pub fn create_profile(&self) -> crate::operation::create_profile::builders::CreateProfileFluentBuilder {
        crate::operation::create_profile::builders::CreateProfileFluentBuilder::new(self.handle.clone())
    }
}
