// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct WeaverBirdPlanningUploadContext {
    /// ID which represents a multi-turn conversation
    pub conversation_id: ::std::option::Option<::std::string::String>,
}
impl WeaverBirdPlanningUploadContext {
    /// ID which represents a multi-turn conversation
    pub fn conversation_id(&self) -> ::std::option::Option<&str> {
        self.conversation_id.as_deref()
    }
}
impl WeaverBirdPlanningUploadContext {
    /// Creates a new builder-style object to manufacture
    /// [`WeaverBirdPlanningUploadContext`](crate::types::WeaverBirdPlanningUploadContext).
    pub fn builder() -> crate::types::builders::WeaverBirdPlanningUploadContextBuilder {
        crate::types::builders::WeaverBirdPlanningUploadContextBuilder::default()
    }
}

/// A builder for
/// [`WeaverBirdPlanningUploadContext`](crate::types::WeaverBirdPlanningUploadContext).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct WeaverBirdPlanningUploadContextBuilder {
    pub(crate) conversation_id: ::std::option::Option<::std::string::String>,
}
impl WeaverBirdPlanningUploadContextBuilder {
    /// ID which represents a multi-turn conversation
    pub fn conversation_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.conversation_id = ::std::option::Option::Some(input.into());
        self
    }

    /// ID which represents a multi-turn conversation
    pub fn set_conversation_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.conversation_id = input;
        self
    }

    /// ID which represents a multi-turn conversation
    pub fn get_conversation_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.conversation_id
    }

    /// Consumes the builder and constructs a
    /// [`WeaverBirdPlanningUploadContext`](crate::types::WeaverBirdPlanningUploadContext).
    pub fn build(self) -> crate::types::WeaverBirdPlanningUploadContext {
        crate::types::WeaverBirdPlanningUploadContext {
            conversation_id: self.conversation_id,
        }
    }
}
