// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct PostErrorReportOutput {}
impl PostErrorReportOutput {
    /// Creates a new builder-style object to manufacture [`PostErrorReportOutput`](crate::operation::post_error_report::PostErrorReportOutput).
    pub fn builder() -> crate::operation::post_error_report::builders::PostErrorReportOutputBuilder {
        crate::operation::post_error_report::builders::PostErrorReportOutputBuilder::default()
    }
}

/// A builder for [`PostErrorReportOutput`](crate::operation::post_error_report::PostErrorReportOutput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct PostErrorReportOutputBuilder {}
impl PostErrorReportOutputBuilder {
    /// Consumes the builder and constructs a [`PostErrorReportOutput`](crate::operation::post_error_report::PostErrorReportOutput).
    pub fn build(self) -> crate::operation::post_error_report::PostErrorReportOutput {
        crate::operation::post_error_report::PostErrorReportOutput {}
    }
}
