// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CreateCustomization`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder) operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`data_reference(DataReference)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::data_reference) / [`set_data_reference(Option<DataReference>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::set_data_reference): (undocumented)
    ///   - [`customization_name(impl Into<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::customization_name) / [`set_customization_name(Option<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::set_customization_name): (undocumented)
    ///   - [`description(impl Into<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::description) / [`set_description(Option<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::set_description): (undocumented)
    ///   - [`profile_arn(impl Into<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::profile_arn) / [`set_profile_arn(Option<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::set_profile_arn): (undocumented)
    ///   - [`tags(Tag)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::tags) / [`set_tags(Option<Vec<Tag>>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::set_tags): (undocumented)
    ///   - [`client_token(impl Into<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::client_token) / [`set_client_token(Option<String>)`](crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::set_client_token): (undocumented)
    /// - On success, responds with [`CreateCustomizationOutput`](crate::operation::create_customization::CreateCustomizationOutput) with field(s):
    ///   - [`customization_arn(Option<String>)`](crate::operation::create_customization::CreateCustomizationOutput::customization_arn): (undocumented)
    /// - On failure, responds with [`SdkError<CreateCustomizationError>`](crate::operation::create_customization::CreateCustomizationError)
    pub fn create_customization(&self) -> crate::operation::create_customization::builders::CreateCustomizationFluentBuilder {
        crate::operation::create_customization::builders::CreateCustomizationFluentBuilder::new(self.handle.clone())
    }
}
