// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`CreateArtifactUploadUrl`](crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlFluentBuilder)
    /// operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`content_md5(impl Into<String>)`](crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlFluentBuilder::content_md5) / [`set_content_md5(Option<String>)`](crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlFluentBuilder::set_content_md5): (undocumented)
    ///   - [`artifact_type(ArtifactType)`](crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlFluentBuilder::artifact_type) / [`set_artifact_type(Option<ArtifactType>)`](crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlFluentBuilder::set_artifact_type): (undocumented)
    /// - On success, responds with
    ///   [`CreateArtifactUploadUrlOutput`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlOutput)
    ///   with field(s):
    ///   - [`upload_id(Option<String>)`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlOutput::upload_id): (undocumented)
    ///   - [`upload_url(Option<String>)`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlOutput::upload_url): (undocumented)
    ///   - [`kms_key_arn(Option<String>)`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlOutput::kms_key_arn): (undocumented)
    /// - On failure, responds with
    ///   [`SdkError<CreateArtifactUploadUrlError>`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlError)
    pub fn create_artifact_upload_url(
        &self,
    ) -> crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlFluentBuilder {
        crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlFluentBuilder::new(
            self.handle.clone(),
        )
    }
}
