// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`GenerateCompletions`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder)
    /// operation. This operation supports pagination; See
    /// [`into_paginator()`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::into_paginator).
    ///
    ///
    /// - The fluent builder is configurable:
    ///   - [`file_context(FileContext)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::file_context) / [`set_file_context(Option<FileContext>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::set_file_context): (undocumented)
    ///   - [`max_results(i32)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::max_results) / [`set_max_results(Option<i32>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::set_max_results): (undocumented)
    ///   - [`next_token(impl Into<String>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::next_token) / [`set_next_token(Option<String>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::set_next_token): (undocumented)
    ///   - [`reference_tracker_configuration(ReferenceTrackerConfiguration)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::reference_tracker_configuration) / [`set_reference_tracker_configuration(Option<ReferenceTrackerConfiguration>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::set_reference_tracker_configuration): (undocumented)
    ///   - [`supplemental_contexts(SupplementalContext)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::supplemental_contexts) / [`set_supplemental_contexts(Option<Vec<SupplementalContext>>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::set_supplemental_contexts): (undocumented)
    ///   - [`customization_arn(impl Into<String>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::customization_arn) / [`set_customization_arn(Option<String>)`](crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::set_customization_arn): (undocumented)
    /// - On success, responds with
    ///   [`GenerateCompletionsOutput`](crate::operation::generate_completions::GenerateCompletionsOutput)
    ///   with field(s):
    ///   - [`completions(Option<Vec<Completion>>)`](crate::operation::generate_completions::GenerateCompletionsOutput::completions): (undocumented)
    ///   - [`next_token(Option<String>)`](crate::operation::generate_completions::GenerateCompletionsOutput::next_token): (undocumented)
    /// - On failure, responds with
    ///   [`SdkError<GenerateCompletionsError>`](crate::operation::generate_completions::GenerateCompletionsError)
    pub fn generate_completions(
        &self,
    ) -> crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder {
        crate::operation::generate_completions::builders::GenerateCompletionsFluentBuilder::new(self.handle.clone())
    }
}
