// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the
    /// [`StartCodeAnalysis`](crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder)
    /// operation.
    ///
    /// - The fluent builder is configurable:
    ///   - [`artifacts(ArtifactType, impl
    ///     Into<String>)`](crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder::artifacts)
    ///     / [`set_artifacts(Option<HashMap<ArtifactType,
    ///     String>>)`](crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder::set_artifacts):
    ///     (undocumented)
    ///   - [`programming_language(ProgrammingLanguage)`](crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder::programming_language) / [`set_programming_language(Option<ProgrammingLanguage>)`](crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder::set_programming_language): (undocumented)
    ///   - [`client_token(impl Into<String>)`](crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder::client_token) / [`set_client_token(Option<String>)`](crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder::set_client_token): (undocumented)
    /// - On success, responds with
    ///   [`StartCodeAnalysisOutput`](crate::operation::start_code_analysis::StartCodeAnalysisOutput)
    ///   with field(s):
    ///   - [`job_id(Option<String>)`](crate::operation::start_code_analysis::StartCodeAnalysisOutput::job_id): (undocumented)
    ///   - [`status(Option<CodeAnalysisStatus>)`](crate::operation::start_code_analysis::StartCodeAnalysisOutput::status): (undocumented)
    ///   - [`error_message(Option<String>)`](crate::operation::start_code_analysis::StartCodeAnalysisOutput::error_message): (undocumented)
    /// - On failure, responds with
    ///   [`SdkError<StartCodeAnalysisError>`](crate::operation::start_code_analysis::StartCodeAnalysisError)
    pub fn start_code_analysis(
        &self,
    ) -> crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder {
        crate::operation::start_code_analysis::builders::StartCodeAnalysisFluentBuilder::new(self.handle.clone())
    }
}
