// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq)]
pub struct UserModificationEvent {
    #[allow(missing_docs)] // documentation missing in model
    pub session_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub request_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub programming_language: ::std::option::Option<crate::types::ProgrammingLanguage>,
    #[allow(missing_docs)] // documentation missing in model
    pub modification_percentage: f64,
    #[allow(missing_docs)] // documentation missing in model
    pub customization_arn: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub timestamp: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl UserModificationEvent {
    #[allow(missing_docs)] // documentation missing in model
    pub fn session_id(&self) -> ::std::option::Option<&str> {
        self.session_id.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn request_id(&self) -> ::std::option::Option<&str> {
        self.request_id.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn programming_language(&self) -> ::std::option::Option<&crate::types::ProgrammingLanguage> {
        self.programming_language.as_ref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn modification_percentage(&self) -> f64 {
        self.modification_percentage
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn customization_arn(&self) -> ::std::option::Option<&str> {
        self.customization_arn.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn timestamp(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.timestamp.as_ref()
    }
}
impl ::std::fmt::Debug for UserModificationEvent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("UserModificationEvent");
        formatter.field("session_id", &self.session_id);
        formatter.field("request_id", &self.request_id);
        formatter.field("programming_language", &self.programming_language);
        formatter.field("modification_percentage", &"*** Sensitive Data Redacted ***");
        formatter.field("customization_arn", &self.customization_arn);
        formatter.field("timestamp", &self.timestamp);
        formatter.finish()
    }
}
impl UserModificationEvent {
    /// Creates a new builder-style object to manufacture
    /// [`UserModificationEvent`](crate::types::UserModificationEvent).
    pub fn builder() -> crate::types::builders::UserModificationEventBuilder {
        crate::types::builders::UserModificationEventBuilder::default()
    }
}

/// A builder for [`UserModificationEvent`](crate::types::UserModificationEvent).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default)]
pub struct UserModificationEventBuilder {
    pub(crate) session_id: ::std::option::Option<::std::string::String>,
    pub(crate) request_id: ::std::option::Option<::std::string::String>,
    pub(crate) programming_language: ::std::option::Option<crate::types::ProgrammingLanguage>,
    pub(crate) modification_percentage: ::std::option::Option<f64>,
    pub(crate) customization_arn: ::std::option::Option<::std::string::String>,
    pub(crate) timestamp: ::std::option::Option<::aws_smithy_types::DateTime>,
}
impl UserModificationEventBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn session_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.session_id = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_session_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.session_id = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_session_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.session_id
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn request_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.request_id = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_request_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.request_id = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_request_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.request_id
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn programming_language(mut self, input: crate::types::ProgrammingLanguage) -> Self {
        self.programming_language = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_programming_language(mut self, input: ::std::option::Option<crate::types::ProgrammingLanguage>) -> Self {
        self.programming_language = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_programming_language(&self) -> &::std::option::Option<crate::types::ProgrammingLanguage> {
        &self.programming_language
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn modification_percentage(mut self, input: f64) -> Self {
        self.modification_percentage = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_modification_percentage(mut self, input: ::std::option::Option<f64>) -> Self {
        self.modification_percentage = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_modification_percentage(&self) -> &::std::option::Option<f64> {
        &self.modification_percentage
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn customization_arn(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.customization_arn = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_customization_arn(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.customization_arn = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_customization_arn(&self) -> &::std::option::Option<::std::string::String> {
        &self.customization_arn
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn timestamp(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.timestamp = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_timestamp(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.timestamp = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_timestamp(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.timestamp
    }

    /// Consumes the builder and constructs a
    /// [`UserModificationEvent`](crate::types::UserModificationEvent).
    pub fn build(self) -> crate::types::UserModificationEvent {
        crate::types::UserModificationEvent {
            session_id: self.session_id,
            request_id: self.request_id,
            programming_language: self.programming_language,
            modification_percentage: self.modification_percentage.unwrap_or_default(),
            customization_arn: self.customization_arn,
            timestamp: self.timestamp,
        }
    }
}
impl ::std::fmt::Debug for UserModificationEventBuilder {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        let mut formatter = f.debug_struct("UserModificationEventBuilder");
        formatter.field("session_id", &self.session_id);
        formatter.field("request_id", &self.request_id);
        formatter.field("programming_language", &self.programming_language);
        formatter.field("modification_percentage", &"*** Sensitive Data Redacted ***");
        formatter.field("customization_arn", &self.customization_arn);
        formatter.field("timestamp", &self.timestamp);
        formatter.finish()
    }
}
