// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct CreateArtifactUploadUrlInput {
    #[allow(missing_docs)] // documentation missing in model
    pub content_md5: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub artifact_type: ::std::option::Option<crate::types::ArtifactType>,
}
impl CreateArtifactUploadUrlInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn content_md5(&self) -> ::std::option::Option<&str> {
        self.content_md5.as_deref()
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn artifact_type(&self) -> ::std::option::Option<&crate::types::ArtifactType> {
        self.artifact_type.as_ref()
    }
}
impl CreateArtifactUploadUrlInput {
    /// Creates a new builder-style object to manufacture
    /// [`CreateArtifactUploadUrlInput`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlInput).
    pub fn builder() -> crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlInputBuilder {
        crate::operation::create_artifact_upload_url::builders::CreateArtifactUploadUrlInputBuilder::default()
    }
}

/// A builder for
/// [`CreateArtifactUploadUrlInput`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlInput).
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
pub struct CreateArtifactUploadUrlInputBuilder {
    pub(crate) content_md5: ::std::option::Option<::std::string::String>,
    pub(crate) artifact_type: ::std::option::Option<crate::types::ArtifactType>,
}
impl CreateArtifactUploadUrlInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    pub fn content_md5(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.content_md5 = ::std::option::Option::Some(input.into());
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_content_md5(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.content_md5 = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_content_md5(&self) -> &::std::option::Option<::std::string::String> {
        &self.content_md5
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn artifact_type(mut self, input: crate::types::ArtifactType) -> Self {
        self.artifact_type = ::std::option::Option::Some(input);
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn set_artifact_type(mut self, input: ::std::option::Option<crate::types::ArtifactType>) -> Self {
        self.artifact_type = input;
        self
    }

    #[allow(missing_docs)] // documentation missing in model
    pub fn get_artifact_type(&self) -> &::std::option::Option<crate::types::ArtifactType> {
        &self.artifact_type
    }

    /// Consumes the builder and constructs a
    /// [`CreateArtifactUploadUrlInput`](crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlInput).
    pub fn build(
        self,
    ) -> ::std::result::Result<
        crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlInput,
        ::aws_smithy_http::operation::error::BuildError,
    > {
        ::std::result::Result::Ok(
            crate::operation::create_artifact_upload_url::CreateArtifactUploadUrlInput {
                content_md5: self.content_md5,
                artifact_type: self.artifact_type,
            },
        )
    }
}
